# Generated by Django 4.0.6 on 2022-07-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='countries',
            new_name='country',
        ),
    ]
